name: CI Pipeline MLOps

on:
  push:
    branches:
      - main

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Check Env
      run: |
        echo "Checking current directory..."
        ls -R

    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn dagshub matplotlib seaborn

    - name: Run mlflow project
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PASSWORD }}
      run: |
        cd MLProject
        mlflow run . --env-manager=local --experiment-name Breast_Cancer_CI_Pipeline --run-name RandomForest_Tuning

    - name: Get latest MLflow run_id
      run: |
        echo "Run ID retrieval processed via MLflow UI"

    - name: Upload to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: training-results
        path: |
          MLProject/*.png
          MLProject/*.txt
          MLProject/mlruns/

    - name: Build Docker Model
      run: |
        docker build -t submission-mlops:latest ./MLProject

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: |
        docker tag submission-mlops:latest ${{ secrets.DOCKER_USERNAME }}/submission-mlops:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/submission-mlops:latest